### ISSUE TITLE
The patch is not downloading

### ISSUE THREAD

**Issue by Rockrez123** [ObserverOfTime/WA2EnglishPatch#11]
### Description

It is telling invalid hastag error.

### Steps to Reproduce

![Screenshot 2022-09-25 131338](https://user-images.githubusercontent.com/114331626/192133518-167aaba4-fa99-4902-8f47-8e86b502224e.png)

**Comment by ObserverOfTime** [comment]
The installer is rate limited and the limit has been reached.
Visit the Discord server for the alternative.
