### ISSUE TITLE
Google drive files

### ISSUE THREAD

**Issue by BigBlackStalk** [ObserverOfTime/WA2EnglishPatch#12]
### Description

I downloaded the files from the google drive, when trying to open the application my screen goes black and then closes. I bought the game from dmm.

Edit: I downloaded the installer and installed the patch in the wa2.exe directory.

### Steps to Reproduce

<img width="960" alt="Screenshot 2023-04-29 033832" src="https://user-images.githubusercontent.com/132120405/235290223-1abe4ebc-2cdb-4f82-af1c-09f1574e3df5.png">

<img width="960" alt="Screenshot 2023-04-29 033851" src="https://user-images.githubusercontent.com/132120405/235290231-55fbbf73-4a81-4ade-ab34-e6a80edc0f31.png">

<img width="960" alt="Screenshot 2023-04-29 014439" src="https://user-images.githubusercontent.com/132120405/235286168-2c344764-208c-4b1d-950a-33ef31cee7da.png">

<img width="960" alt="Screenshot 2023-04-29 014654" src="https://user-images.githubusercontent.com/132120405/235286172-ea69e91f-466f-4ab4-bf26-f9aea26e9556.png">

<img width="960" alt="Screenshot 2023-04-29 014734" src="https://user-images.githubusercontent.com/132120405/235286184-c3e5c70e-82c8-4b07-b680-3dedf5270982.png">

**Comment by ObserverOfTime** [comment]
Install the game and install the patch in the folder of the game.
