### ISSUE TITLE
Patch WA2_en.exe opens but the window stays black and closes

### ISSUE THREAD

**Issue by intheclouds-101** [ObserverOfTime/WA2EnglishPatch#2]
## Description

I have installed the WA2_patch.exe patch (previously installed the game), and then ran WA2_en.exe and the window opens with a black screen and then after a few seconds closes.

## Steps to Reproduce

run patch WA2_patch.exe then run WA2_en.exe.

## Log File

[WA2_Patch_Log_2019-03-11_18.42.14.log](https://github.com/TodokanaiTL/WA2EnglishPatch/files/2953816/WA2_Patch_Log_2019-03-11_18.42.14.log)

**Comment by ObserverOfTime** [comment]
Judging by the log file, you didn't select the directory of WA2 during installation.

**Comment by intheclouds-101** [comment]
@ObserverOfTime I did select the WA2_patch.exe directory during installation

**Comment by ObserverOfTime** [comment]
You're supposed to select the WA2.exe directory...

**Comment by intheclouds-101** [comment]
Yup got it! Done Thank You! @ObserverOfTime
