### ISSUE TITLE
Can't connect and download En.pak

### ISSUE THREAD

**Issue by Haldeyr** [ObserverOfTime/WA2EnglishPatch#3]
the installer can download the videos perfectly, but always fails to connect and download the en.pak. tried different versions to no avail

**Comment by ObserverOfTime** [comment]
Can you [download the file](https://www.dropbox.com/s/rkl4hwij4mshef2/en.pak?dl=1) from a browser?

**Comment by Haldeyr** [comment]
Yes thank you it's working perfectly. Great work <3

**Comment by xunknownx** [comment]
getting the same error, and this link https://www.dropbox.com/s/rkl4hwij4mshef2/en.pak?dl=1 is not working either.
