### ISSUE TITLE
Can't run the patch when you don't have WA2 installed

### ISSUE THREAD

**Issue by forvy** [ObserverOfTime/WA2EnglishPatch#4]
## Description
You should be able to point the WA2 directory even if you don't have it installed.
Can't run the patch when you don't have WA2 installed (even when you have it from an existing copy from another machine) seems weird. When you can execute the game fine:
![image](https://user-images.githubusercontent.com/17746819/73995042-154e7800-498a-11ea-80f1-8798fd13198e.png)
![image](https://user-images.githubusercontent.com/17746819/73995079-31521980-498a-11ea-9473-1fe9c6b2522e.png)

## Steps to Reproduce

![image](https://user-images.githubusercontent.com/17746819/73994846-82add900-4989-11ea-94cd-3a0cb1ca5435.png)

Just run the patch.
## Possible Fix

You should be able to point the WA2 directory even if you don't have it installed.

**Comment by ObserverOfTime** [comment]
Use the DMM patch.
