### ISSUE TITLE
Paks failed to download.

### ISSUE THREAD

**Issue by redpotato15** [ObserverOfTime/WA2EnglishPatch#5]
## Description

Pak files fail to download and continuing the installer set up alerts me with back to back pop ups that those 8 paks appear corrupt..
## Steps to Reproduce

![wa2img](https://user-images.githubusercontent.com/75517605/101236607-20e8f900-3698-11eb-8772-28463936ecc2.png)
![wa2img2](https://user-images.githubusercontent.com/75517605/101236610-23e3e980-3698-11eb-87da-38d99cc3cae5.png)
I've tried both installers listed on the site. Both reach this point. Retrying to run the installers again gets me these same messages.
Thank you for your time in advance.

**Comment by ObserverOfTime** [comment]
Try the [rewrite alpha](https://ci.appveyor.com/api/buildjobs/n0j62vobjs9ogie7/artifacts/build%2Fbin%2Fnative%2FreleaseExecutable%2FWA2_patch.exe).

**Comment by redpotato15** [comment]
Tried what you sent and got this. 

![wa2 img 3](https://user-images.githubusercontent.com/75517605/101268117-5a1b7a80-3725-11eb-8a6f-0c968fb69a14.png) 
![wa2 img 4 5](https://user-images.githubusercontent.com/75517605/101268307-19246580-3727-11eb-8401-c8cc3e46cf04.png)

Retried applying the original 2 patches and then one you sent. (individually) 

![wa2 img 6](https://user-images.githubusercontent.com/75517605/101268664-8a661780-372b-11eb-8e5d-13dbc6b0856c.png)
![wa2 img 7](https://user-images.githubusercontent.com/75517605/101268668-8d610800-372b-11eb-8e66-e8b764ad49f8.png)

Here's my log. From a recent attempt.

[WA2_Patch_Log_2020-12-05_17.44.10.log](https://github.com/TodokanaiTL/WA2EnglishPatch/files/5648121/WA2_Patch_Log_2020-12-05_17.44.10.log)

Thank you for your time on this.

**Comment by ObserverOfTime** [comment]
Run [this build](https://ci.appveyor.com/api/buildjobs/9uhqhsihe1k9wn4a/artifacts/build%2Fbin%2Fnative%2FreleaseExecutable%2FWA2_patch.exe) from `cmd` with `.\WA2_patch.exe  2>&1 > WA2_patch.log` and post that log file.

**Comment by redpotato15** [comment]
Running the site patches and then cmd running the sent build? Just making sure. 
wa2 patch (site patch) and ran the build thru cmd.
My log for this.
[WA2_Patch_Log_2020-12-07_03.29.28.log](https://github.com/TodokanaiTL/WA2EnglishPatch/files/5651991/WA2_Patch_Log_2020-12-07_03.29.28.log)

wa2 DMM patch and ran the build thru cmd.
My log.
[WA2_Patch_Log_2020-12-07_04.05.05.log](https://github.com/TodokanaiTL/WA2EnglishPatch/files/5652004/WA2_Patch_Log_2020-12-07_04.05.05.log)

Both runs of the patch + sent build got me this. 
I should note that the sent build on its own also gave me this result after attempting twice to "install selected".
![WA2 dmm patch to sent build](https://user-images.githubusercontent.com/75517605/101339416-018ecf00-3844-11eb-9b94-4d60978fc4c0.png)

Again, thank you for your time on this.

**Comment by ObserverOfTime** [comment]
Neither of those logs is the one I want. I want the log generated when you run the new build with that command.

**Comment by redpotato15** [comment]
My bad. I got it now.

[WA2_patch.log](https://github.com/TodokanaiTL/WA2EnglishPatch/files/5656558/WA2_patch.log)

**Comment by ObserverOfTime** [comment]
You either didn't run the second build I sent you, or didn't include `2>&1` in the command.
The file you posted is missing all the curl debug logs I need.

**Comment by redpotato15** [comment]
I had copy & pasted the command as it was posted to cmd. `.\WA2_patch.exe 2>&1 > WA2_patch.log`
I typed it out this time.
![cmdcap](https://user-images.githubusercontent.com/75517605/101560245-70754080-3988-11eb-8301-c23ffd18477f.png)

I deleted any previous patches and builds i had in my downloads and re-downloaded the 2nd build.
The results are pretty much the same. 
[WA2_patch.log](https://github.com/TodokanaiTL/WA2EnglishPatch/files/5663214/WA2_patch.log)

Sorry for my ignorance on this. I don't know why logs lines are missing. 
If you feel like we reach an impasse im okay with taking this issue up another time. Don't wanna bug you too much.

**Comment by ObserverOfTime** [comment]
My bad, I just realised the order is wrong.
It needs to be `.\WA2_patch.exe > WA2_patch.log 2>&1`.

**Comment by redpotato15** [comment]
It's cool, here you go.
[WA2_patch.log](https://github.com/TodokanaiTL/WA2EnglishPatch/files/5670572/WA2_patch.log)

**Comment by ObserverOfTime** [comment]
Download [this build](https://ci.appveyor.com/api/buildjobs/ln1rdn63t8atr8h3/artifacts/build%2Fbin%2Fnative%2FdebugExecutable%2FWA2_patch.exe) along with [this DLL](https://upload.disroot.org/r/dELKc8b2#OnBmTGkoxA+iCJQrnU28BWGc4AWoxVcTvX0hrVMSsuo=) and run it with the same command. It may or may not work this time.

**Comment by redpotato15** [comment]
The DLL will work as long as its in the same directory as the build, right? (Not familiar with this.) Moved them from my downloads to their own folder.
[WA2_patch.log](https://github.com/TodokanaiTL/WA2EnglishPatch/files/5677357/WA2_patch.log)

I got this error after the patch had finished doing its thing and I exited the window.

![Runtime error wa2](https://user-images.githubusercontent.com/75517605/101870837-06a39500-3b48-11eb-8f5a-808f8dfe0465.png)

**Comment by ObserverOfTime** [comment]
If [this build](https://ci.appveyor.com/api/buildjobs/2tvh10xuwork83xi/artifacts/build%2Fbin%2Fnative%2FdebugExecutable%2FWA2_patch.exe) doesn't work see if you can manually download the files:
https://github.com/TodokanaiTL/WA2EnglishPatch/blob/2e8c6e4417e5cea799d1390cfeb551144e01a5a4/src/nativeMain/kotlin/CURL.kt#L20-L30

**Comment by redpotato15** [comment]
Unfortunately the build won't download the exe for me and the progress bar for the en.pak goes into limbo. Waited it out for 15 mins with no change.
[WA2_patch.log](https://github.com/TodokanaiTL/WA2EnglishPatch/files/5682538/WA2_patch.log)

![wa2 11](https://user-images.githubusercontent.com/75517605/101976365-2bf8d780-3c0a-11eb-9e6b-f143409dad77.png)

I am able to download all the files manually. 
Would just dropping the ev000 and ev150 pak files into the games exe directory in conjunction with a previous build that downloaded previous files work fine?

**Comment by ObserverOfTime** [comment]
Yes, you can just drop them in the folder.

**Comment by redpotato15** [comment]
Okay. The game is working properly now. 
Thanks for your work and time on this. Have a good holiday dude!
