### ISSUE TITLE
404 not found

### ISSUE THREAD

**Issue by Smithjs5** [ObserverOfTime/WA2EnglishPatch#6]
### Description

Hi There,

I've installed the windows 10 compatible version of the game in Japanese and downloaded the patch. When I open the patch and go through the wizard, I get to the download and get the below Error.

<img width="563" alt="Screenshot 2021-12-31 183408" src="https://user-images.githubusercontent.com/96923097/147835650-8ca83134-0097-4403-9176-43f2a4bd5afa.png">

Everything is there that I am aware of and I'm not sure what to do.

Thanks,
Kind regards

### Steps to Reproduce

6 steps as below,
<img width="561" alt="1" src="https://user-images.githubusercontent.com/96923097/147835866-33594dda-3d78-44ae-b656-dbd5666d74a6.png">
<img width="560" alt="2" src="https://user-images.githubusercontent.com/96923097/147835871-a19f3c62-6931-43ed-a00a-444283cd2657.png">
<img width="566" alt="3" src="https://user-images.githubusercontent.com/96923097/147835873-b8643ee3-80a1-4324-adc9-576047b04bca.png">
<img width="558" alt="4" src="https://user-images.githubusercontent.com/96923097/147835874-72d5cb08-078f-42d5-8b22-bc40cf15b31f.png">
<img width="562" alt="5" src="https://user-images.githubusercontent.com/96923097/147835877-00801f00-0be9-4b30-b186-1c68de751929.png">
<img width="565" alt="6" src="https://user-images.githubusercontent.com/96923097/147835880-0c1f0f09-6f22-40fe-a4c6-74cb42edd234.png">

**Comment by picar0jsu** [comment]
![image](https://user-images.githubusercontent.com/57172324/147835972-9244c3d0-86c0-4cc2-96b3-d23571795a1c.png)
Likewise, please assist. Thank you!

**Comment by ObserverOfTime** [comment]
The downloads have been rate limited. You can grab the files from [here](https://drive.google.com/drive/folders/1qVbhZO0evMqxSUNtHB-javndjpPg_mYH).

**Comment by Makein** [comment]
Same error again...

**Comment by ObserverOfTime** [comment]
Same solution…
