### ISSUE TITLE
Installer crashing

### ISSUE THREAD

**Issue by jordanian-kid** [ObserverOfTime/WA2EnglishPatch#7]
### Description

When I open the installer and try to download the files it freezes and after a while says "Operation timed out" and then crashes.

### Steps to Reproduce

![Screenshot 2022-01-04 113031](https://user-images.githubusercontent.com/97125732/148113491-ff532a20-f90d-40bb-899e-64bee8fb405b.png)

**Comment by jordanian-kid** [comment]
Also I saw alot of other people saying to put WA2_exe in directory or somein. I don't know what this directory thing is, sorry I'm new to visual novels.

**Comment by ObserverOfTime** [comment]
It was most likely blocked by your firewall/proxy/antivirus/ISP.
