### ISSUE TITLE
Download Failed: 404 Not Found

### ISSUE THREAD

**Issue by Todokanai** [ObserverOfTime/WA2EnglishPatch#8]
### Description

exactly what it says, I run the patch and get this error

### Steps to Reproduce

![image](https://user-images.githubusercontent.com/20650946/150796482-b2962401-b82a-4b28-9b2c-6e47eb008e91.png)

**Comment by ObserverOfTime** [comment]
The public links were shut down by dropbox. See https://github.com/TodokanaiTL/WA2EnglishPatch/issues/6#issuecomment-1003440056.
